In [2]:
# Numpy 
# Numpy is a powerful library for numerical computing in Python. 
# It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions 
# to operate on these arrays efficiently.

# Importing Numpy
import numpy as np

# Creating Numpy Arrays
# You can create Numpy arrays from Python lists or tuples using the np.array() function.
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

1D Array: [1 2 3 4 5]


In [3]:
print(type(arr1))  # Output: <class 'numpy.ndarray'>
print(arr1.shape)  # Output: (5,) - This indicates that it's a 1D array with 5 elements.

<class 'numpy.ndarray'>
(5,)


In [4]:
# convert arr1 to 2D array
arr2 = arr1.reshape(5, 1)
print("2D Array:\n", arr2)
print(arr2.shape)  # Output: (5, 1) - This indicates that it's a 2D array with 5 rows and 1 column.

2D Array:
 [[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [5]:
# change it to 2D array with 1 row and 5 columns
arr3 = arr1.reshape(1, 5)
print("2D Array with 1 row and 5 columns:\n", arr3)

2D Array with 1 row and 5 columns:
 [[1 2 3 4 5]]


In [6]:
# You can also create multi-dimensional arrays (e.g., 2D arrays) using nested lists.
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [7]:
# change the above array to 3D array with 1 layer, 2 rows and 3 columns
arr3d = arr2.reshape(1, 2, 3)
print("3D Array:\n", arr3d)

3D Array:
 [[[1 2 3]
  [4 5 6]]]


In [9]:
elements = np.arange(1,10,2) # Output: array([1, 3, 5, 7, 9]) - This creates a 1D array with values from 1 to 9 (exclusive) with a step of 2.

arr4 = elements.reshape(1, 5) # Output: array([[1, 3, 5, 7, 9]]) - This reshapes the array into a 2D array with 1 row and 5 columns.
print("Reshaped Array:\n", arr4)

Reshaped Array:
 [[1 3 5 7 9]]


In [10]:
# ones and zeros with np.ones() and np.zeros()
# You can create arrays filled with ones or zeros using np.ones() and np.zeros() functions.
ones_array = np.ones((3, 4))  # This creates a 3x4 array filled with ones.
zeros_array = np.zeros((2, 5))  # This creates a 2x5 array filled with zeros.
print("Array of Ones:\n", ones_array)
print("Array of Zeros:\n", zeros_array)

Array of Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array of Zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
# Numpy vectorized operations
# Numpy allows you to perform element-wise operations on arrays without the need for explicit loops.
# For example, you can add two arrays together:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
sum_arr = arr1 + arr2  # This will add the corresponding elements of arr1 and arr2 together.
print("Result of addition:", sum_arr)  # Output: [5 7 9]

sub_arr = arr1 - arr2  # This will subtract the corresponding elements of arr2 from arr1.
print("Result of subtraction:", sub_arr)  # Output: [-3 -3 -3]

mul_arr = arr1 * arr2  # This will multiply the corresponding elements of arr1 and arr2 together.
print("Result of multiplication:", mul_arr)  # Output: [ 4 10 18]

div_arr = arr1 / arr2  # This will divide the corresponding elements of arr1 by arr2.
print("Result of division:", div_arr)  # Output: [0.25 0.4  0.5 ]

Result of addition: [5 7 9]
Result of subtraction: [-3 -3 -3]
Result of multiplication: [ 4 10 18]
Result of division: [0.25 0.4  0.5 ]


In [12]:
# Universal Functions (ufuncs)
# Numpy provides a set of universal functions (ufuncs) that operate element-wise on arrays. These functions are optimized for performance and can be used to perform various mathematical operations.
# For example, you can use the np.sqrt() function to compute the square root of each element in an array:
arr = np.array([1, 4, 9, 16])
sqrt_arr = np.sqrt(arr)  # This will compute the square root of each element in the array.
print("Square root of the array:", sqrt_arr)  # Output: [1. 2. 3. 4.]

exponential_arr = np.exp(arr)  # This will compute the exponential of each element in the array.
print("Exponential of the array:", exponential_arr)  # Output: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]

sine_arr = np.sin(arr)  # This will compute the sine of each element in the array.
print("Sine of the array:", sine_arr)  # Output: [ 0.84147098  0.90929743  0.14112001 -0.28790332]

nat_log_arr = np.log(arr)  # This will compute the natural logarithm of each element in the array.
print("Natural logarithm of the array:", nat_log_arr)  # Output: [0.         1.38629436 2.19722458 2.77258872]

Square root of the array: [1. 2. 3. 4.]
Exponential of the array: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
Sine of the array: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]
Natural logarithm of the array: [0.         1.38629436 2.19722458 2.77258872]


In [13]:
## Slicing and Indexing
# Numpy arrays can be sliced and indexed in a similar way to Python lists, but with more powerful capabilities. You can access specific elements, rows, columns, or even sub-arrays using
# slicing and indexing.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:\n", arr)

# Accessing specific elements
print("Element at row 0, column 1:", arr[0, 1])  # Output: 2 - This accesses the element in the first row and second column.

# Slicing rows and columns
print("First row:", arr[0, :])  # Output: [1 2 3] - This slices the first row of the array.
print("Second column:", arr[:, 1])  # Output: [2 5 8] - This slices the second column of the array.
print("Sub-array (first two rows and first two columns):\n", arr[:2, :2])  # Output: [[1 2] [4 5]] - This slices the first two rows and first two columns of the array. 

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 0, column 1: 2
First row: [1 2 3]
Second column: [2 5 8]
Sub-array (first two rows and first two columns):
 [[1 2]
 [4 5]]


In [14]:
# Modify array elements
arr[0, 0] = 10  # This modifies the element at row 0, column 0 to be 10.
print("Modified Array:\n", arr)

Modified Array:
 [[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [15]:
# Normalization
# Normalization is a technique used to scale the values of an array to a specific range,
# often between 0 and 1. This can be useful for various applications, such as machine learning or data visualization.
# You can normalize an array using the following formula:
# normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
arr = np.array([1, 2, 3, 4, 5])
normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
print("Normalized Array:", normalized_arr)  # Output: [0.  0.25 0.5 0.75 1.] - 
# This normalizes the array to a range between 0 and 1.

Normalized Array: [0.   0.25 0.5  0.75 1.  ]


In [16]:
# standard deviation
arr = np.array([1, 2, 3, 4, 5])
std_dev = np.std(arr)  # This computes the standard deviation of the array.
print("Standard Deviation:", std_dev)  # Output: 1.414213562373095 - 
# This is the standard deviation of the array, which measures the amount of variation or
#  dispersion of the elements from the mean.

# mean 
mean_value = np.mean(arr)  # This computes the mean (average) of the array.
print("Mean:", mean_value)  # Output: 3.0 - This is the mean of the array, which is the sum of the elements divided by the number of elements.

# variance
variance_value = np.var(arr)  # This computes the variance of the array.
print("Variance:", variance_value)  
# Output: 2.0 - This is the variance of the array, which measures the average squared deviation of each element from the mean.

Standard Deviation: 1.4142135623730951
Mean: 3.0
Variance: 2.0


In [17]:
# Formula for mean: mean = sum(arr) / len(arr)
# Formula for variance: variance = sum((arr - mean) ** 2) / len(arr)
# The mean is calculated by summing all the elements in the array and dividing by the number of elements.
# The variance is calculated by taking the difference between each element and the mean, 
# squaring that difference, and then averaging the squared differences.
# Formula for standard deviation: std_dev = sqrt(variance)
# The standard deviation is calculated by taking the square root of the variance,
#  which gives a measure of the spread of the data around the mean.

In [18]:
# Logical operations
# Numpy allows you to perform logical operations on arrays, 
# which can be useful for filtering and selecting elements based on conditions.

data = np.array([1, 2, 3, 4, 5])
# Create a boolean array where the condition is True for elements greater than 2
condition = data > 2
print("Condition (data > 2):", condition)  
# Output: [False False  True  True  True] - This creates a boolean array where each element is True if the
# corresponding element in the original array satisfies the condition (greater than 2) and False otherwise.

Condition (data > 2): [False False  True  True  True]
