# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [3]:
### Assignment 1: Array Creation and Manipulation

# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

import numpy as np

first_array = np.random.randint(1,21, size=(5,5))
print("Original Array:")
print(first_array)

first_array[:, 2] =  1
print("\nArray after replacing third column with 1:")
print(first_array)

second_array = np.arange(1,17).reshape(4,4)
print("\nOriginal Array:")
print(second_array)


np.fill_diagonal(second_array, 0)
print("\nArray after replacing diagonal elements with 0:")
print(second_array)


Original Array:
[[20 10 14 17 12]
 [10 18 11 19 18]
 [ 6  2  3  5 19]
 [ 4  6 19 12 13]
 [ 7  7 13 11 11]]

Array after replacing third column with 1:
[[20 10  1 17 12]
 [10 18  1 19 18]
 [ 6  2  1  5 19]
 [ 4  6  1 12 13]
 [ 7  7  1 11 11]]

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Array after replacing diagonal elements with 0:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [4]:
### Assignment 2: Array Indexing and Slicing

# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
# 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

third_array = np.arange(1,37).reshape(6,6)
print("Third Array:")
print(third_array)

sub_third_array = third_array[2:5,1:4]
print("/nSub_third_array:")
print(sub_third_array)

fourth_array = np.random.randint(1,20, size=(5,5))
print("/nFourth Array:")
print(fourth_array)

border_elements = np.concatenate((fourth_array[0,:], fourth_array[-1,:], fourth_array[1:-1,0], fourth_array[1:-1,-1]))
print("\nBorder elements:")
print(border_elements)

# Note: The above code assumes that the border elements are defined as the first and last rows, and the first and last columns of the array.
# Depending on the specific requirements, you may need to adjust the slicing to include or exclude certain elements.
# For example, if you want to include the corners only once, you can modify the code as follows:
# fourth_array[1:-1,-1] to exclude the corners from the last column, 
# and fourth_array[1:-1,0] to exclude the corners from the first column.

Third Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
/nSub_third_array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]
/nFourth Array:
[[19 10 11 18 17]
 [19 13 13 13  9]
 [ 2 17  8 11 16]
 [ 4 14  6  2  9]
 [15  9 16 11  6]]

Border elements:
[19 10 11 18 17 15  9 16 11  6 19  2  4  9 16  9]


In [7]:
### Assignment 3: Array Operations

# 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

first_array = np.random.randint(1,20, size=(3,4))
second_array = np.random.randint(1,20, size=(3,4))

print(first_array)
print(second_array)
print(first_array + second_array)
print(first_array - second_array)
print(first_array * second_array)
print(first_array / second_array)

third_array = np.arange(1,17).reshape(4,4)
print(third_array)
row_sum = np.sum(third_array, axis=1)
column_sum = np.sum(third_array, axis=0)
print("Row-wise sum:", row_sum)
print("Column-wise sum:", column_sum)



[[ 4  1 19 13]
 [14 18 15 18]
 [15  8 17 13]]
[[ 1  8 18  3]
 [ 8 12  9  1]
 [16 16 16  5]]
[[ 5  9 37 16]
 [22 30 24 19]
 [31 24 33 18]]
[[ 3 -7  1 10]
 [ 6  6  6 17]
 [-1 -8  1  8]]
[[  4   8 342  39]
 [112 216 135  18]
 [240 128 272  65]]
[[ 4.          0.125       1.05555556  4.33333333]
 [ 1.75        1.5         1.66666667 18.        ]
 [ 0.9375      0.5         1.0625      2.6       ]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]


In [8]:
### Assignment 4: Statistical Operations

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

first_array = np.random.randint(1,20, size=(5,5))
print(first_array)
mean = np.mean(first_array)
median = np.median(first_array)
std_dev = np.std(first_array)
variance = np.var(first_array)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)

second_array = np.arange(1,10).reshape(3,3)
print(second_array)
normalized_array = (second_array - np.mean(second_array)) / np.std(second_array)
print("Normalized Array:")
print(normalized_array)

[[11  7 10 12  1]
 [10  5 17  1 16]
 [11  9 18 17  7]
 [ 7 16 14 14 12]
 [ 6  7 12  5 15]]
Mean: 10.4
Median: 11.0
Standard Deviation: 4.758150901348127
Variance: 22.64
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [10]:
### Assignment 5: Broadcasting

# 1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
# 2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

first_array = np.random.randint(1,20, size=(3,3))
print(first_array)
one_d_array = np.array([1, 2, 3])
result_addition = first_array + one_d_array
print("Result of addition:")
print(result_addition)

second_array = np.random.randint(1,20, size=(4,4))
print(second_array)
one_d_array = np.array([1, 2, 3, 4])
result_subtraction = second_array - one_d_array
print("Result of subtraction:")
print(result_subtraction)

# Note: The above code assumes that the 1D array has the same number of elements as the corresponding dimension of the 2D array.
# If the shapes are not compatible for broadcasting, you may need to reshape the 1D array to match the dimensions of the 2D array before performing the operation. For example, you can reshape the 1D array to have a shape of (3, 1) for addition
# and a shape of (1, 4) for subtraction to ensure that the broadcasting works correctly.

# why for row addition same 1d array and column deletion same 1d array?
# The reason for using the same 1D array for both row addition and column subtraction is
# that the operations are performed on different dimensions of the 2D array.
# In the case of row addition, we want to add the 1D array to each row of the 2D array, so the shape of the 1D array should match the
# number of columns in the 2D array. In the case of column subtraction, we want to subtract the 1D array from each column of the 2D array, so the shape of the 1D array should match the number of rows in the 2D array.
# By using the same 1D array for both operations, we can easily perform the desired calculations without needing to create separate arrays for each operation. The broadcasting mechanism in NumPy will automatically handle the alignment of the arrays based on their shapes, allowing us to perform the operations efficiently.
# If we were to use different 1D arrays for row addition and column subtraction, we would need to ensure that the shapes of those arrays are compatible with the dimensions of the 2D array for each operation, which could lead to confusion and potential errors in the code. Using the same 1D array simplifies the process and reduces the chances of shape mismatches.

# i still dont understand column row addition and subtraction with broadcasting. can you explain with an example?
# Sure! Let's go through an example to understand row addition and column subtraction with broadcasting in NumPy.
# Let's say we have a 2D array (matrix) of shape (3, 3):
# [[1, 2, 3],
#  [4, 5, 6],
#  [7, 8, 9]]
# Now, let's say we want to add a 1D array [10, 20, 30] to each row of this 2D array.
# The shape of the 1 D array is (3,), which matches the number of columns in the 2D array. 
# When we perform the addition, NumPy will automatically broadcast the 1D array across each row of the 2D array, resulting in:
# [[11, 22, 33],
#  [14, 25, 36],
#  [17, 28, 39]]

# Now, let's say we want to subtract a 1D array [1, 2, 3] from each column of the original 2D array.
# The shape of the 1D array is (3,), which matches the number of rows in the 2D array.
# When we perform the subtraction, NumPy will automatically broadcast the 1D array across each column of the 2D array, resulting in:
# [[0, 1, 2],
#  [3, 4, 5],
#  [6, 7, 8]]   

# examples with different dimensional arrays like 3,4 and 4,5
# Let's say we have a 2D array of shape (3, 4):
# [[1, 2, 3, 4],
#  [5, 6, 7, 8],
#  [9, 10, 11, 12]]
# Now, let's say we want to add a 1D array [10, 20, 30, 40] to each row of this 2D array.
# The shape of the 1D array is (4,), which matches the number of columns in the 2D array. 
# When we perform the addition, NumPy will automatically broadcast the 1D array across each row of the 2D array, resulting in:
# [[11, 22, 33, 44],
#  [15, 26, 37, 48],
#  [19, 30, 41, 52]]    

# Now, let's say we want to subtract a 1D array [1, 2, 3, 4] from each column of the original 2D array.
# The shape of the 1D array is (4,), which matches the number of rows in the 2D array.
# When we perform the subtraction, NumPy will automatically broadcast the 1D array across each column of the 2D array, resulting in:
# [[0, 1, 2, 3],
#  [4, 5, 6, 7],
#  [8, 9, 10, 11]]

# why didnt it subtract columnwise and why rowwise?
# The reason for the behavior you observed is that the shape of the 1D array determines how it will be broadcasted when performing operations with a 2D array.
# When you add a 1D array to a 2D array, NumPy checks the shape of the 1D array and determines how to align it with the dimensions of the 2D array. If the shape of the 1D array matches the number of columns in
# the 2D array, it will be broadcasted across each row. If the shape of the 1D array matches the number of rows in the 2D array, it will be broadcasted across each column.
# In the case of row addition, since the shape of the 1D array matches the number of columns in the 2D array, it is broadcasted across each row. In the case of column subtraction, since the shape of the 1D array matches the number of rows in the 2D array, it is broadcasted across each column.
# If you want to perform column-wise addition or row-wise subtraction, you can reshape the 1D array to match the appropriate dimension of the 2D array. For example, if you want to perform column-wise addition,
# you can reshape the 1D array to have a shape of (3, 1) for a 2D array of shape (3, 4). This way, the 1D array will be broadcasted across each column instead of each row. Similarly, for row-wise subtraction, you can reshape the 1D array to have a shape of (1, 4) for a 2D array of shape (3, 4) to ensure that it is broadcasted across each row instead of each column.

# Show in terms of same 3,3 array column or row takes precedence in terms of subtraction or addition?
# In terms of precedence for subtraction or addition, it depends on the shape of the 1D array and how it is broadcasted with the 2D array. 
# If the shape of the 1D array matches the number of columns in the 2D array, then row addition or subtraction will take precedence, and the 1D array will be broadcasted across each row of the 2D array. 
# If the shape of the 1D array matches the number of rows in the 2D array, then column addition or subtraction will take precedence, and the 1D array will be broadcasted across each column of the 2D array.
# For example, if we have a 2D array of shape (3, 3) and a 1D array of shape (3,), then row addition or subtraction will take precedence, and the 1D array will be broadcasted across each row of the 2D array.
# If we have a 2D array of shape (3, 3) and a 1D array of shape (3,), then column addition or subtraction will take precedence, and the 1D array will be broadcasted across each column of the 2D array.

[[13  5  8]
 [ 8 16 16]
 [ 1 12  6]]
Result of addition:
[[14  7 11]
 [ 9 18 19]
 [ 2 14  9]]
[[11 13 12  2]
 [ 2  8  5 10]
 [ 9  4 18  3]
 [12  6  6 14]]
Result of subtraction:
[[10 11  9 -2]
 [ 1  6  2  6]
 [ 8  2 15 -1]
 [11  4  3 10]]


In [12]:
### Assignment 6: Linear Algebra

# 1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
# 2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

first_array = np.random.randint(1,20, size=(3,3))
print("First Array:")
print(first_array)
determinant = np.linalg.det(first_array)
inverse = np.linalg.inv(first_array)
eigenvalues = np.linalg.eigvals(first_array)
print("Determinant:", determinant)
print("Inverse:", inverse)
print("Eigenvalues:", eigenvalues)

# mathe formula for determinant, inverse and eigenvalues
# The determinant of a 3x3 matrix [[a, b, c], [d, e, f], [g, h, i]] can be calculated using the formula:
# determinant = a(ei - fh) - b(di - fg) + c(dh - eg)
# The inverse of a 3x3 matrix [[a, b, c], [d, e, f], [g, h, i]] can be calculated using the formula:
# inverse = (1/determinant) * [[ei - fh, ch - bi, bf - ce], [fg - di, ai - cg, cd - af], [dh - eg, bg - ah, ae - bd]]
# The eigenvalues of a 3x3 matrix can be calculated by solving the characteristic equation, which is derived from the determinant of the matrix subtracted by a scalar (the eigenvalue) multiplied by the identity matrix. The characteristic equation is given by:
# det([[a - λ, b, c], [d, e - λ, f], [g, h, i - λ]]) = 0
# where λ represents the eigenvalues. Solving this equation will yield the eigenvalues of the matrix.

second_array = np.random.randint(1,20, size=(2,3))
third_array = np.random.randint(1,20, size=(3,2))
print("Second Array:")
print(second_array)
print("Third Array:")
print(third_array)
result_matrix_multiplication = np.dot(second_array, third_array)
print("Result of Matrix Multiplication:")
print(result_matrix_multiplication)

# np.dot in data science is used for performing matrix multiplication. It takes two arrays as input and returns the dot product of the two arrays. In the context of data science, np.dot is commonly used for various operations such as:
# 1. Linear Regression: np.dot is used to calculate the predicted values in linear regression by multiplying the feature matrix with the coefficient vector.
# 2. Neural Networks: np.dot is used in the forward pass of neural networks to calculate the activations of each layer by multiplying the input with the weights of the layer.
# 3. Principal Component Analysis (PCA): np.dot is used to calculate the covariance matrix in PCA by multiplying the centered data matrix with its transpose.
# 4. Similarity Measures: np.dot is used to calculate the cosine similarity between two vectors by multiplying the vectors and dividing by their magnitudes.
# Overall, np.dot is a fundamental function in data science for performing matrix operations and is widely used in various algorithms and techniques for data analysis and machine learning.    

First Array:
[[ 5  1  5]
 [18 15  6]
 [15 10  7]]
Determinant: -35.99999999999987
Inverse: [[-1.25       -1.19444444  1.91666667]
 [ 1.          1.11111111 -1.66666667]
 [ 1.25        0.97222222 -1.58333333]]
Eigenvalues: [24.39837106 -0.47896828  3.08059722]
Second Array:
[[18 17  2]
 [ 5  1  4]]
Third Array:
[[ 2 13]
 [19 12]
 [ 3  3]]
Result of Matrix Multiplication:
[[365 444]
 [ 41  89]]


In [13]:
### Assignment 7: Advanced Array Manipulation

# 1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
# 2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

first_array = np.arange(1,10).reshape(3,3)
print("Original Array:")
print(first_array)
reshaped_array_1 = first_array.reshape(1, 9)
print("\nReshaped Array (1, 9):")
print(reshaped_array_1)
reshaped_array_2 = reshaped_array_1.reshape(9, 1)
print("\nReshaped Array (9, 1):")
print(reshaped_array_2)

second_array = np.random.randint(1,20, size=(5,5))
print("Original Array:")
print(second_array)
flattened_array = second_array.flatten()
print("\nFlattened Array:")
print(flattened_array)
reshaped_array = flattened_array.reshape(5, 5)
print("\nReshaped Array (5, 5):")
print(reshaped_array)

# flatten and reshape in data science are used for manipulating the shape of arrays to fit the requirements of different algorithms and models.
# 1. Flatten: The flatten function is used to convert a multi-dimensional array into a one-dimensional array. This is often necessary when working with certain machine learning algorithms that require input data to
# be in a specific shape. For example, when working with image data, you may need to flatten a 2D array of pixel values into a 1D array before feeding it into a neural network.
# 2. Reshape: The reshape function is used to change the shape of an array without changing its data. This is useful when you need to adjust the dimensions of your data to fit
# the requirements of a specific algorithm or model. For example, if you have a 1D array of features and you want to feed it into a model that expects a 2D array, you can use reshape to change the shape of the array accordingly.
# Overall, flatten and reshape are essential tools in data science for preparing and manipulating data to ensure compatibility with various algorithms and models, allowing for efficient data processing and analysis.

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reshaped Array (1, 9):
[[1 2 3 4 5 6 7 8 9]]

Reshaped Array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
Original Array:
[[19  2 10 18  4]
 [10  2  3  8  6]
 [ 5 15 16  4 16]
 [17 16 16  6 10]
 [15 17  5  5  4]]

Flattened Array:
[19  2 10 18  4 10  2  3  8  6  5 15 16  4 16 17 16 16  6 10 15 17  5  5
  4]

Reshaped Array (5, 5):
[[19  2 10 18  4]
 [10  2  3  8  6]
 [ 5 15 16  4 16]
 [17 16 16  6 10]
 [15 17  5  5  4]]


In [14]:
### Assignment 8: Fancy Indexing and Boolean Indexing

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
# 2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

first_array = np.random.randint(1,20, size=(5,5))
print("Original Array:")
print(first_array)
corners = first_array[[0, -1], :][:, [0, -1]]
print("\nCorners of the Array:")
print(corners)

second_array = np.random.randint(1,20, size=(4,4))
print("\nOriginal Array:")
print(second_array)
second_array[second_array > 10] = 10
print("\nArray after setting elements greater than 10 to 10:")
print(second_array)

Original Array:
[[10 10 17  1  9]
 [12 12 11 18 16]
 [11 13  1 12  8]
 [17 16  1  4  4]
 [17  5  8  6 15]]

Corners of the Array:
[[10  9]
 [17 15]]

Original Array:
[[10  5  9  4]
 [13 15  4 12]
 [ 1 11 17  9]
 [19 13  4  4]]

Array after setting elements greater than 10 to 10:
[[10  5  9  4]
 [10 10  4 10]
 [ 1 10 10  9]
 [10 10  4  4]]


In [15]:
### Assignment 9: Structured Arrays

# 1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
# 2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

first_array = np.array([('Alice', 25, 55.5), ('Bob', 30, 75.0), ('Charlie', 22, 68.0)],
                       dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
print("Original Structured Array:")
print(first_array)
sorted_array = np.sort(first_array, order='age')
print("\nStructured Array sorted by age:")
print(sorted_array)

second_array = np.array([(1, 2), (3, 4), (5, 6)],
                        dtype=[('x', 'i4'), ('y', 'i4')])
print("\nOriginal Structured Array:")
print(second_array)
euclidean_distances = np.sqrt((second_array['x'][:, np.newaxis] - second_array['x'])**2 + (second_array['y'][:, np.newaxis] - second_array['y'])**2)
print("\nEuclidean distances between each pair of points:")
print(euclidean_distances)

Original Structured Array:
[('Alice', 25, 55.5) ('Bob', 30, 75. ) ('Charlie', 22, 68. )]

Structured Array sorted by age:
[('Charlie', 22, 68. ) ('Alice', 25, 55.5) ('Bob', 30, 75. )]

Original Structured Array:
[(1, 2) (3, 4) (5, 6)]

Euclidean distances between each pair of points:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [17]:
### Assignment 10: Masked Arrays

# 1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
# 2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

first_array = np.random.randint(1,20, size=(4,4))
masked_array = np.ma.masked_greater(first_array, 10)
print("Original Array:")
print(first_array)
print("\nMasked Array (elements greater than 10 are masked):")
print(masked_array)
sum_unmasked = masked_array.sum()
print("\nSum of unmasked elements:", sum_unmasked)

second_array = np.random.randint(1,20, size=(3,3))
masked_array = np.ma.masked_array(second_array, mask=np.eye(3, dtype=bool))
print("\nOriginal Array:")
print(second_array)
print("\nMasked Array (diagonal elements are masked):")
print(masked_array)
mean_unmasked = masked_array.mean()
filled_array = masked_array.filled(mean_unmasked)
print("\nArray after replacing masked elements with mean of unmasked elements:")
print(filled_array)

# What is masking in data science?
# Masking in data science refers to the process of hiding or ignoring certain elements in a dataset
# based on specific conditions or criteria. This is often done to handle missing or invalid data, or to focus on a subset of the data for analysis. 
# Masking can be achieved using various techniques, such as boolean indexing, where a boolean array is used to select or exclude certain elements from the dataset. 
# Masking allows data scientists to work with clean and relevant data, improving the accuracy and efficiency of their analyses and models.

Original Array:
[[16 15 11 13]
 [ 5 19  2  4]
 [14 16  1 18]
 [ 7 15  8 12]]

Masked Array (elements greater than 10 are masked):
[[-- -- -- --]
 [5 -- 2 4]
 [-- -- 1 --]
 [7 -- 8 --]]

Sum of unmasked elements: 27

Original Array:
[[18  7 12]
 [10 15 10]
 [ 5  9 12]]

Masked Array (diagonal elements are masked):
[[-- 7 12]
 [10 -- 10]
 [5 9 --]]

Array after replacing masked elements with mean of unmasked elements:
[[ 8  7 12]
 [10  8 10]
 [ 5  9  8]]


In [ ]:
# it didnt replace mean of unmasked elements with masked elements. why?
# The reason the masked elements were not replaced with the mean of the unmasked elements is that
# the masked array is designed to ignore the masked elements during calculations. When you compute the mean of the unmasked elements, it only considers the unmasked values and does not include the masked values in the calculation.
# Therefore, when you try to replace the masked elements with the mean of the unmasked elements
# using the filled method, it does not modify the original masked array but instead returns a new array with the masked elements replaced by the specified value (in this case, the mean of the unmasked elements).
# To replace the masked elements in the original masked array, you can use the filled method and
# assign the result back to the original masked array. For example:
# masked_array = masked_array.filled(mean_unmasked)
# This way, the original masked array will be updated with the mean of the unmasked elements replacing the masked elements.